#Uncomment the next line to define a global platform for your project
#platform :ios, '8.0'

target 'RunrMVP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'AFNetworking'
    pod 'BDBOAuth1Manager'
#Pods for RunrMVP

  target 'RunrMVPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RunrMVPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
